#pragma once

#define CSCRIPTPROP_RETNUL	0x0001
#define CSCRIPTPROP_RETREF	0x0002
#define CSCRIPTPROP_RETVAL	0x0004
#define CSCRIPTPROP_ARG1	0x0008
#define CSCRIPTPROP_ARG1S	0x0010
#define CSCRIPTPROP_ARG2	0x0020
#define CSCRIPTPROP_NARG1	0x0040
#define CSCRIPTPROP_NARG2	0x0080
#define CSCRIPTPROP_NARGS	0x0100
#define CSCRIPTPROP_UNUSED	0x0200
#define CSCRIPTPROP_DUPE	0x0400
#define CSCRIPTPROP_READO	0x0800
#define CSCRIPTPROP_WRITEO	0x1000

#define DECLARE_LISTREC_REF(a)
#define DECLARE_LISTREC_REF2(a)
#define CSCRIPT_EXEC_DEF void Exec
#define CSCRIPT_CLASS_DEF1 void Exec
#define CSCRIPT_CLASS_DEF2(a)
#define CSCRIPT_CLASS_IMP0(a,b,c)
#define CSCRIPT_CLASS_IMP1(a,b,c,d,e)
#define DECLARE_LISTREC_TYPE(a)
#define CSCRIPT_PROP_IMP(a,b,c)
#define CSCRIPT_PROPX_IMP(a,b,c)
#define CSCRIPT_METHOD_IMP(a,b,c)
