#pragma once

#define CSCRIPT_CLASS_IMP1(TYPE,_PROPS,_METHODS,_HELP)
#define DECLARE_LISTREC_REF(a)
#define DECLARE_LISTREC_REF2(a)
#define CSCRIPT_EXEC_DEF void Exec
#define CSCRIPT_CLASS_DEF1 void Exec
#define CSCRIPT_CLASS_DEF2 void Exec
#define DECLARE_LISTREC_TYPE(a)